

title: Rikuto Nonomura
description: Rikuto Nonomura, 野々村 陸大
copyright: (c) Rikuto Nonomura
twitter_username: ricknon22
github_username:  RickNon

# Build settings
plugins:
  - jekyll-feed
languages: ["ja", "en"]
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: ja